[project]
name = "openai-ocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "openai>=1.59.3",
    "pyproject-toml>=0.1.0",
]

[dependency-groups]
dev = [
    "ruff>=0.8.5",
]
